- 1~45개의 번호 중 무작위로 6개씩 생성되는 번호 세트를 총 10개 출력하기

In [41]:
import numpy as np

In [15]:
for i in range(10):
    arr = np.arange(46)
    num = np.random.permutation(arr)
    print(num[:6])


[40 42 36  1 22 25]
[18  5 38 30 12 45]
[24 26 13  3  7 23]
[34 39 18 41 36 16]
[37  8 28 31 13 40]
[17 34 10 41 44  9]
[32 13  8 20  9 16]
[29 38 10 24 33  1]
[34 10 32 26 44 31]
[23 12  6 27 20 33]


계단 오르 내리기

- 동전을 던졌을 때 앞이 나오면 계단 1칸 올라가기
- 동전을 던졌을 때 뒤가 나오면 계단 1칸 내려가기
- 현재 위치 position = 0
- 1000번 동전을 던졌을 때의 위치의 히스토리 : walk 리스트

In [38]:
import random as rd

walk = [] # 미리 만들어 놓은 리스트
step = 0

for i in range(1000):
    coin = rd.randint(0,1)
    if coin == 1: 
        step=step + 1
    else:
        step=step - 1
        
    walk.append(step) # 미리 만들어 놓은 리스트에 결과값 step을 추가해야함 안그러면 마지막 값을 조회 할 수 없음
    

In [39]:
walk[-1] # 인덱스로 마지막 값을 뽑아냄

-46

- np.random.randint() : 동전의 앞뒤 결정
- np.where() : 동전의 앞뒤 조건에 따른 step 결정
- np.cumsum() : 현재 위치의 히스토리

In [55]:
coin=np.random.randint(0,2,1000)
step=np.where(coin<=0, -1, 1)
walk=np.cumsum(step)
walk

array([ -1,  -2,  -3,  -2,  -3,  -4,  -3,  -2,  -3,  -4,  -5,  -4,  -5,
        -6,  -7,  -6,  -7,  -8,  -9,  -8,  -9,  -8,  -9, -10, -11, -12,
       -13, -14, -13, -12, -13, -12, -13, -14, -13, -14, -15, -14, -13,
       -14, -15, -16, -17, -16, -15, -14, -13, -14, -13, -14, -13, -12,
       -11, -10,  -9, -10, -11, -10, -11, -10,  -9,  -8,  -7,  -8,  -9,
       -10,  -9,  -8,  -7,  -8,  -7,  -6,  -7,  -8,  -7,  -8,  -7,  -6,
        -5,  -6,  -5,  -4,  -5,  -4,  -5,  -6,  -7,  -6,  -7,  -8,  -7,
        -6,  -5,  -6,  -7,  -6,  -7,  -8,  -7,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,  -1,   0,   1,   0,  -1,  -2,  -3,  -4,  -3,
        -4,  -3,  -4,  -3,  -2,  -3,  -4,  -5,  -4,  -3,  -4,  -3,  -2,
        -3,  -2,  -1,  -2,  -3,  -2,  -3,  -4,  -3,  -4,  -3,  -2,  -3,
        -2,  -1,  -2,  -1,  -2,  -1,  -2,  -3,  -4,  -3,  -2,  -1,  -2,
        -1,   0,   1,   2,   1,   2,   3,   4,   5,   4,   3,   2,   3,
         2,   1,   0,   1,   0,   1,   0,   1,   2,   1,   2,   

In [56]:
min(walk)

-18

In [57]:
max(walk)

5

- 딕셔너리 -> 시리즈 변환 (index, values 출력)

In [61]:
import pandas as pd

In [62]:
dict_data = {'a':1, 'b':2, 'c':3}

In [63]:
sr = pd.Series(dict_data)
sr

a    1
b    2
c    3
dtype: int64

- 리스트 -> 시리즈 변환 (index, values 출력)

In [64]:
list_data = ['2019-01-02', 3.14, 'ABC', 100, True]

In [65]:
sr = pd.Series(list_data)
sr

0    2019-01-02
1          3.14
2           ABC
3           100
4          True
dtype: object

- 튜플 -> 시리즈 변환 (index, values 출력

In [66]:
tuple_data = ('영인', '2010-05-01', '여', True)

In [67]:
sr = pd.Series(tuple_data)
sr

0            영인
1    2010-05-01
2             여
3          True
dtype: object

- 튜플 -> 시리즈 변환 (index 설정)

In [68]:
tuple_data = ('영인', '2010-05-01', '여', True)
index_name = ['이름', '생년월일', '성별', '학생여부']

In [69]:
sr = pd.Series(tuple_data,index = ['이름', '생년월일', '성별', '학생여부'])
sr

이름              영인
생년월일    2010-05-01
성별               여
학생여부          True
dtype: object

- 시리즈 원소 선택

In [ ]:
# 슬라이스 색인을 통해 '2010-05-01', '여' 값이 나오도록

In [82]:
sr[1:3] # 완전히 두개만 나오게는 못하나 ???

생년월일    2010-05-01
성별               여
dtype: object

In [ ]:
# 색인을 통해 '영인'값이 나오도록

In [73]:
sr[0]

'영인'

- 딕셔너리 -> 데이터프레임

In [86]:
import pandas as pd

In [87]:
dict_data = {'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9], 'c3':[10,11,12], 'c4':[13,14,15]}

In [88]:
a = pd.DataFrame(dict_data)
a

c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

- 행인덱스/열이름 설정

In [89]:
df = pd.DataFrame([[15, '남', '덕영중'], [17, '여', '수리중']], 
                   index=['준서', '예은'],
                   columns=['나이', '성별', '학교'])
df

나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [ ]:
# 준서, 예은 -> 학생1, 학생2

In [91]:
df.index=['학생1','학생2']
df

나이 성별   학교
학생1  15  남  덕영중
학생2  17  여  수리중

In [ ]:
# 나이, 성별, 학교 -> 연령, 남녀, 소속

In [92]:
df.columns = ['연령', '남녀', '소속']
df

연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [ ]:
# 행인덱스/열이름 변경
# rename 사용하여 변경 (부분적으로 수정하고 싶을 때)

In [101]:
df = pd.DataFrame([[15, '남', '덕영중'], [17, '여', '수리중']], 
                   index=['준서', '예은'],
                   columns=['나이', '성별', '학교'])
df

나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [102]:
df.rename(index={'준서':'재영'},inplace=True)
df

나이 성별   학교
재영  15  남  덕영중
예은  17  여  수리중

In [103]:
df.rename(columns={'나이':'레벨'},inplace=True)
df

레벨 성별   학교
재영  15  남  덕영중
예은  17  여  수리중