# 파이토치 기본

- 파이토치 공식 문서 : [http://pytorch.org/](http://pytorch.org/)
- Numpy 배열과 유사한 Tensor
- GPU에서 빠른 속도로 처리되는 Tensor
- 자동 미분 계산 기능(오차역전파용)
- 그 외 신경망을 구축하기 위한 모듈들
- 직관적인 인터페이스

In [2]:
import torch
import numpy as np

## 1. 텐서

- 텐서는 파이토치의 데이터 형태
- 텐서는 단일 데이터 형식으로 된 자료들의 다차원 행렬
- 텐서는 간단한 명령어(변수 뒤에 .cuda()를 추가)를 사용해서 GPU로 연산을 수행하게 할 수 있음


tensor_examples.svg

- 텐서 생성

In [ ]:
x = torch.empty(5, 4)
x

tensor([[1.9334e-34, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [ ]:
torch.ones(3, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.zeros(2)

tensor([0., 0.])

In [ ]:
torch.rand(5, 6)

tensor([[0.1504, 0.6944, 0.9067, 0.2519, 0.7489, 0.4857],
        [0.6655, 0.0464, 0.4624, 0.7112, 0.2064, 0.2395],
        [0.2642, 0.5918, 0.2364, 0.2088, 0.8559, 0.9488],
        [0.4645, 0.3831, 0.2108, 0.6438, 0.0200, 0.7222],
        [0.2347, 0.3237, 0.1445, 0.2406, 0.1975, 0.2614]])

In [ ]:
torch.randn(5, 6)

tensor([[-2.2323, -0.1869, -0.4078,  0.8248, -0.3399,  0.5711],
        [-0.7350, -0.4945, -0.0871, -0.6058, -1.0068, -0.4136],
        [-0.2983,  1.2150, -0.9592,  1.2088,  0.4193,  1.1145],
        [ 1.1983,  0.9470, -1.9783,  1.9980,  0.2604, -0.0535],
        [-1.1738,  2.9347, -1.0627, -0.0777,  0.5297, -0.5073]])

In [ ]:
l = [3, 4]
torch.tensor(l)

tensor([3, 4])

In [ ]:
n = np.array([4, 5, 6])
torch.tensor(n)

tensor([4, 5, 6])

- 텐서 사이즈

In [ ]:
x = torch.empty(5, 4)
x.shape

torch.Size([5, 4])

In [ ]:
x.size()

torch.Size([5, 4])

In [ ]:
x.size()[0], x.size()[1]

(5, 4)

In [ ]:
x.size(0), x.size(1)

(5, 4)

- 텐서 타입

In [ ]:
type(x)

torch.Tensor

In [ ]:
x.dtype # 개별 원소의 타입

torch.float32

In [ ]:
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [ ]:
a.dtype

torch.int64

In [ ]:
b = torch.tensor([1.1, 2.1, 3.1])
b

tensor([1.1000, 2.1000, 3.1000])

In [ ]:
b.dtype

torch.float32

In [ ]:
a_f = torch.tensor([1, 2, 3], dtype=torch.float32)
a_f.dtype

torch.float32

In [ ]:
c = torch.Tensor([1, 2, 3]) # 대문자 Tensor는 기본 데이터 타입이 float32, 데이터 타입을 함수 내부에서 지정할 수 없음
c

tensor([1., 2., 3.])

In [ ]:
c.dtype

torch.float32

In [ ]:
l_t = torch.LongTensor([1, 2])
f_t = torch.FloatTensor([1, 2])
d_t = torch.DoubleTensor([1, 2])
l_t.dtype, f_t.dtype, d_t.dtype

(torch.int64, torch.float32, torch.float64)

In [ ]:
g = d_t.type(torch.FloatTensor) # type() : 형변환 함수
g.dtype

torch.float32

- 텐서 연산

In [ ]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)

In [ ]:
x

tensor([[0.8587, 0.0647],
        [0.3441, 0.5599]])

In [ ]:
y

tensor([[0.3171, 0.8494],
        [0.6733, 0.9485]])

In [ ]:
x+y

tensor([[1.1757, 0.9141],
        [1.0174, 1.5084]])

In [ ]:
torch.add(x, y)

tensor([[1.1757, 0.9141],
        [1.0174, 1.5084]])

In [ ]:
y.add(x)

tensor([[1.1757, 0.9141],
        [1.0174, 1.5084]])

In [ ]:
y

tensor([[0.3171, 0.8494],
        [0.6733, 0.9485]])

In [ ]:
y.add_(x) # _ : inplace 연산
y

tensor([[1.1757, 0.9141],
        [1.0174, 1.5084]])

- 텐서 색인

In [ ]:
y[0]

tensor([1.1757, 0.9141])

In [ ]:
y[:, 1:]

tensor([[0.9141],
        [1.5084]])

In [ ]:
y[:, 1]

tensor([0.9141, 1.5084])

- 텐서의 크기 변환(reshaping)

In [ ]:
x = torch.rand(8, 8)
x.size()

torch.Size([8, 8])

In [ ]:
a = x.view(64) # numpy reshape 기능
a.size()

torch.Size([64])

In [ ]:
b = x.view(16, 4)
b.size()


torch.Size([16, 4])

In [ ]:
c = x.view(-1, 4)
c.size()

torch.Size([16, 4])

In [ ]:
d = x.view(-1, 4, 4)
d.size()

torch.Size([4, 4, 4])

In [ ]:
d.resize_(16, 4)

In [ ]:
d.size()

torch.Size([16, 4])

In [ ]:
e = d.view(4, 4, 4)
e.size()

torch.Size([4, 4, 4])

In [ ]:
f = torch.flatten(e)
f.size()

torch.Size([64])

In [ ]:
f = torch.flatten(e, 0) #0번 dim부터 flatten
f.size()

torch.Size([64])

In [ ]:
g = torch.flatten(e, 1) #1번 dim부터 flatten
g.size()

torch.Size([4, 16])

- 텐서에서 넘파이 배열로, 넘파이 배열에서 텐서로

In [ ]:
type(g)

torch.Tensor

In [ ]:
g_n = g.numpy() # tensor를 numpy로
type(g_n)

numpy.ndarray

In [ ]:
g_t = torch.from_numpy(g_n) # numpy로부터 tensor로
type(g_t)

torch.Tensor

- 단일 텐서에서 값으로 변환하기

In [ ]:
x = torch.ones(1)
x

tensor([1.])

In [ ]:
x.item()

1.0

## 2. 역전파

In [5]:
x = torch.ones(2, 2, requires_grad = True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [6]:
y = x + 1
y

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)

In [7]:
z = 2*y**2
z

tensor([[8., 8.],
        [8., 8.]], grad_fn=<MulBackward0>)

In [8]:
l = z.mean()
l

tensor(8., grad_fn=<MeanBackward0>)

In [9]:
l.backward()

In [ ]:
# y 는 x에 대한 식, z는 y에 대한 식, l은 z에 대한 식
# 최종식은 합성함수로 표현될 수 있으므로 l은 x로 표현이 가능하고 미분도 가능하다.

In [10]:
x.grad   

tensor([[2., 2.],
        [2., 2.]])